### ISSUE TITLE
Ghost CoPilot instances after rebuilding Docker container

### ISSUE THREAD

**Issue by Yoriyari** [socfortress/CoPilot#193]
hi! I'm having a strange issue - when I access CoPilot in my browser by either a local IP or Docker IP and then rebuild the Docker container running CoPilot, the CoPilot instance behind the accessed IP stops working as long as the host machine is running. the interface is still there but never loads any components, as pictured below, with the only feedback being "An error occurred. Please try again later." 

![image](https://github.com/socfortress/CoPilot/assets/29695473/cf5ddaec-cd8d-415a-8cb8-ba65d893ee96)

if I log out of that instance, the login button likewise just returns that ambiguous error. CoPilot can still be used normally on a different IP, until the container is rebuilt, after which that different IP's CoPilot instance also runs into the same error. the broken CoPilot instances remain accessible at the same IPs even after stopping the Docker container running CoPilot, while CoPilot IPs that haven't broken become unable to connect as expected. checking the running processes and containers on Docker doesn't reveal any ghost instances.

**Comment by Yoriyari** [comment]
I rebuilt the Docker container because I adjusted the settings of the container, such as the translation between ports inside and outside the container. I do not have much experience so I would not be surprised if there is a better way to update settings, apologies!

Regardless, should CoPilot be leaving these empty instances hogging accessed IPs when this happens?

**Comment by taylorwalton** [comment]
You should only need to update the settings in the compose file. For example if you wanted to map to port 8443, you would change the `copilot-frontend` to similar to the below:

```
copilot-frontend:
        image: ghcr.io/socfortress/copilot-frontend:latest
        environment:
            - SERVER_HOST=${SERVER_HOST:-localhost} # Set the domain name of your server
        ports:
            - "80:80"
            - "8443:443"
```
